from departments.base import DepartmentSpec
from departments.product_analytics.agents import DEPARTMENT_ID, on_task_received

SPEC = DepartmentSpec(
    department_id=DEPARTMENT_ID,
    display_name="Product & Data Analytics",
    description=(
        "Answers ad hoc questions about company-wide task/SLA metrics, "
        "grounded in real Firestore task counts. Chart specs are built "
        "deterministically, never generated by the LLM."
    ),
    accepted_task_types=["analytics_query"],
    memory_namespace="product_analytics",
    on_task_received=on_task_received,
)

__all__ = ["SPEC"]
