"""Product & Data Analytics: answers ad hoc questions about company-wide
task metrics. The chart spec is built deterministically from the same
counts the LLM answer is grounded in — never generated by the LLM itself,
since having a model restate numbers it was already handed is a pure
hallucination risk with no upside over just computing it directly."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from app.adk_agents.factory import build_tiered_stage_agents
from app.adk_agents.runtime import run_agent_turn
from app.models import Task, TaskResult, TaskStatus
from app.services import store
from app.services.session_service import FirestoreSessionService
from departments.base import audited_task
from departments.product_analytics.schemas import ChartSpec

DEPARTMENT_ID = "product_analytics"

_PROMPTS_DIR = Path(__file__).parent / "prompts"


def _load_prompt(name: str) -> str:
    return (_PROMPTS_DIR / f"{name}.md").read_text(encoding="utf-8")


metrics_agents = build_tiered_stage_agents(
    "analytics_metrics_analyst",
    instruction=_load_prompt("metrics_analyst"),
    description="Product & Data Analytics pipeline stage: metrics analyst",
)

_session_service = FirestoreSessionService()

_ALL_STATUSES = [s.value for s in TaskStatus]


def _counts_by_department_and_status(org_id: str) -> dict[str, dict[str, int]]:
    counts: dict[str, dict[str, int]] = defaultdict(lambda: {s: 0 for s in _ALL_STATUSES})
    for task in store.list_tasks(org_id):
        department = task.assignee or "unassigned"
        counts[department][task.status.value] += 1
    return {dept: dict(status_counts) for dept, status_counts in counts.items()}


def _build_chart_spec(counts: dict[str, dict[str, int]]) -> ChartSpec:
    labels = sorted(counts.keys())
    series = {status: [counts[label][status] for label in labels] for status in _ALL_STATUSES}
    return ChartSpec(chart_type="bar", labels=labels, series=series)


@audited_task(DEPARTMENT_ID)
async def on_task_received(org_id: str, task: Task) -> TaskResult:
    tier = task.model_tier  # ADR-0013: the CEO picks flash/pro at create_task time
    # No attachment wiring here: this department answers questions about
    # deterministic Firestore counts, not user-facing content.
    counts = _counts_by_department_and_status(org_id)
    chart = _build_chart_spec(counts)

    prompt = json.dumps({"question": task.description, "counts": counts})
    answer = await run_agent_turn(metrics_agents[tier], _session_service, org_id, DEPARTMENT_ID, prompt)

    return TaskResult(
        success=True,
        summary=answer,
        data={"chart": chart.model_dump(), "raw_counts": counts},
        needs_human=False,
    )
