from typing import Any

from pydantic import BaseModel


class ChartSpec(BaseModel):
    """A minimal, frontend-renderable chart spec. Built deterministically in
    agents.py from real aggregate counts, never generated by an LLM — an
    LLM restating numbers it was already given is a pure hallucination risk
    with zero value over just computing the spec directly."""

    chart_type: str  # "bar" for now — the only shape task-by-department counts need
    labels: list[str]
    series: dict[str, list[int]]  # series name (task status) -> counts aligned with labels


class AnalyticsResult(BaseModel):
    answer: str
    chart: ChartSpec
    raw_counts: dict[str, Any]
